# Zola configuration
# isaagi.cloud

base_url = "https://isaagi.cloud"
title = "Istasha"
description = "Systems engineer. Memory safety, secure allocation, Rust."
default_language = "en"

compile_sass = true
minify_html = true
generate_feed = true
feed_filename = "rss.xml"

[markdown]
highlight_code = true
highlight_theme = "ayu-dark"
render_emoji = false
external_links_target_blank = true

[extra]
author = "Istasha"
email = "67969809+The-Istasha@users.noreply.github.com"
github = "https://github.com/The-Istasha"
